spring:
  application:
    name: shareit
#  config:
#    activate:
#      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

spring.output.ansi.enabled: always

logbook:
  format:
    style: http
  filter:
    enabled: true

logging:
  level:
    root: INFO
    org.zalando.logbook: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.springframework.orm.transaction: INFO
    org.springframework.orm.transaction.interceptor: INFO



#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    driver-class-name: "org.postgresql.Driver"
#    username: "dbuser"
#    password: "12345"
#    url: "jdbc:postgresql://localhost:5432/shareit"
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true