spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.output.ansi.enabled=always
logging.level.root=INFO
logging.level.org.zalando.logbook=TRACE
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=INFO
logging.level.org.springframework.orm.jpa.JpaTransactionManager=INFO
logbook.format.style=http
logbook.filter.enabled=true
# TODO Append connection to DB
#spring.datasource.driverClassName
#spring.datasource.url
#spring.datasource.username
#spring.datasource.password
spring:
application.name:later
main.banner-mode:OFF
jpa:
show-sql:true
properties:
hibernate.jdbc.time_zone:UTC
datasource:
username:"dbuser"
password:"12345"
url:"jdbc:postgresql://localhost:5432/later"
driver-class-name:"org.postgresql.Driver"

