spring:
  application:
    name: shareit-server
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: "org.postgresql.Driver"
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:5432/shareit"

spring.output.ansi.enabled: always

server:
  port: 9090

logbook:
  format:
    style: http
  filter:
    enabled: true

logging:
  level:
    root: INFO
    org.zalando.logbook: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.springframework.orm.transaction: INFO
    org.springframework.orm.transaction.interceptor: INFO
